metrics_logger:
  type: dcvt.common.utils.tracking.MlFLowMinioLogger
  # experiment_name: human_segmentation

experiment_name: rf_signs_detection

model:
  # Better use definite names, not paths like other objects - better backward compatibility
  type: Yolo4Tiny

  strides: [16, 32]
  anchors: [4,5, 11,16, 24,27, 30,38, 44,47, 58,63]
  anchor_masks: [[0, 1, 2], [3, 4, 5]]

  infer_sz_hw: [192, 256]
  channels: 3
  labels: [
    "forward",
    "left",
    "right",
    "brick",
    "forward_left",
    "forward_right",
    "traffic_light",
  ]

  # Loss
  bbox_loss:
    ciou_ratio: 1
    gt_match_max_ratio: 4
    
    bbox_rate: 0.05
    cls_rate: 0.58
    obj_rate: 1.0

train:
  # pretrained: face_detection_last.pth
  skip_eval_epochs: 5

  batch: 32
  subdivisions: 1
  lr: 3e-4
  epochs: 3000

  optimizer:
    type: torch.optim.Adam

  scheduler:
    type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 200
    T_mult: 2

  # Artifacts
  artifacts_dir: artifacts

  # For torch.DataLoader
  num_workers: -1
  pin_memory: True

  augmentation:
    type: src.transform.AlbuAugmentation
    fill_value: 127
    min_area_px: 25
    min_visibility: 0.1

  data:
    max_targets: 30
    scale_div: 255
  
  checkpoints_metrics:
    - name: "eval/map50"
    - name: "eval/map75"

dataset:
  # Root configuration - applied to all
  config:
    show_stats: True

  train:
    - type: cvat
      root_dirpath: data/RF19
      img_sdirpath: Images
      ann_sfpath: annotations.xml

    - type: cvat
      root_dirpath: data/RF17
      img_sdirpath: Images
      ann_sfpath: annotations.xml

    - type: cvat
      root_dirpath: data/RF_sim_1
      img_sdirpath: Images
      ann_sfpath: annotations.xml

    - type: cvat
      root_dirpath: data/RF19_test
      img_sdirpath: Images
      ann_sfpath: annotations.xml

    - type: cvat
      root_dirpath: data/RF20_test
      img_sdirpath: Images
      ann_sfpath: annotations.xml

  valid:
    - type: cvat
      root_dirpath: data/RF19_test
      img_sdirpath: Images
      ann_sfpath: annotations.xml
      
    - type: cvat
      root_dirpath: data/RF20_test
      img_sdirpath: Images
      ann_sfpath: annotations.xml

